[[headers]]
for = "/apple-app-site-association"
[headers.values]
Content-Type = "application/json"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/apple-app-site-association"
status = 200
to = "/.well-known/apple-app-site-association.json"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
